<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 02/09/2018
 * Time: 4:00 AM
 */

$url = new stdClass();

$url->dashboard = "index.php?page=dashboard&lang=en";
$url->income ="index.php?page=income&lang=en";
$url->expenses ="index.php?page=expenses&lang=en";
$url->salary = "index.php?page=salary&lang=en";
$url->cashbook = "index.php?page=cash-book&lang=en";
$url->bank = "index.php?page=bank&lang=en";
$url->budget ="index.php?page=budget&lang=en";
$url->setting ="index.php?page=setting&lang=en";