<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 01/09/2018
 * Time: 11:46 PM
 */

$servername = SERVER;
$username = USERNAME;
$password = PASSWORD;
$database = DATABASE;

// Create connection
$conn = new mysqli($servername, $username, $password,$database);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
session_start();
//echo "Connected successfully";