<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 02/09/2018
 * Time: 4:27 AM
 */

function calender_year($conn){

    $sql="SELECT * FROM get_calender_yr";
    $result = $conn->query($sql);
    while($row = $result->fetch_assoc()){
        echo "<option value='".$row['c_year']."'>".$row['c_year']."</option>";
    }
}

function calender_month($conn){

    $sql ="SELECT * FROM get_calender_month";
    $result = $conn->query($sql);
    while($row = $result->fetch_assoc()){
        echo "<option value='".$row['monthID']."'>".$row['c_month']."</option>";
    }
}


function income_categories($conn){

    $id = $_SESSION['user-id'];

    $sql="SELECT * FROM get_income_category where userID='$id'";
    $result = $conn->query($sql);
    while($row = $result->fetch_assoc()){
        echo "<option value='".$row['cataID']."'>".$row['category']."</option>";
    }
}

function expenses_categories($conn){

    $id = $_SESSION['user-id'];

    $sql="SELECT * FROM get_expenses_category where userID='$id'";
    $result = $conn->query($sql);
    while($row = $result->fetch_assoc()){
        echo "<option value='".$row['cataID']."'>".$row['category']."</option>";
    }
}

function payment_type($conn){

    $sql="SELECT * FROM `get_payment_type` where payID= 1 or payID=2 ";
    $result = $conn->query($sql);
    while($list = $result->fetch_assoc()){
        echo"<option value='".$list['payID']."'>".$list['payment_type']."</option>";
    }

}

function utilities_bill_type($conn){

    $sql="SELECT * FROM `get_payment_type` where payID = 3 or payID = 4";
    $result = $conn->query($sql);
    while($list = $result->fetch_assoc()){
        echo"<option value='".$list['payID']."'>".$list['payment_type']."</option>";
    }
}
