<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 02/09/2018
 * Time: 2:08 AM
 */
?>
<li>
    <a href="<?php echo $url->dashboard;?>">
        <i class="now-ui-icons design_app"></i>
        <p><?php echo $button->dashboard;?></p>
    </a>
</li>
<li>
    <a href="<?php echo $url->income;?>">
        <i class="now-ui-icons education_atom"></i>
        <p><?php echo $button->income;?></p>
    </a>
</li>
<li>
    <a href="<?php echo $url->expenses;?>">
        <i class="now-ui-icons education_atom"></i>
        <p><?php echo $button->expenses;?></p>
    </a>
</li>
<li>
    <a href="<?php echo $url->cashbook;?>">
        <i class="now-ui-icons location_map-big"></i>
        <p><?php echo $button->cashbook;?></p>
    </a>
</li>
<li>
    <a href="<?php echo $url->bank;?>">
        <i class="now-ui-icons ui-1_bell-53"></i>
        <p><?php echo $button->bank;?></p>
    </a>
</li>
<li>
    <a href="<?php echo $url->budget;?>">
        <i class="now-ui-icons ui-1_bell-53"></i>
        <p><?php echo $button->budget;?></p>
    </a>
</li>
<li>
    <a href="<?php echo $url->setting;?>">
        <i class="now-ui-icons ui-1_bell-53"></i>
        <p><?php echo $button->setting;?></p>
    </a>
</li>