<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 02/09/2018
 * Time: 2:08 AM
 */
?>
<li>
    <a href="<?php echo $url->dashboard;?>">
        <i class="now-ui-icons design_app"></i>
        <p><?php echo $button->dashboard;?></p>
    </a>
</li>
<li>
    <a href="<?php echo $url->salary;?>">
        <i class="now-ui-icons education_atom"></i>
        <p><?php echo $button->salary;?></p>
    </a>
</li>
<li>
    <a href="<?php echo $url->cashbook;?>">
        <i class="now-ui-icons location_map-big"></i>
        <p><?php echo $button->cashbook;?></p>
    </a>
</li>
<li>
    <a href="<?php echo $url->bank;?>">
        <i class="now-ui-icons ui-1_bell-53"></i>
        <p><?php echo $button->bank;?></p>
    </a>
</li>
<li class="active ">
    <a href="./user.html">
        <i class="now-ui-icons users_single-02"></i>
        <p>User Profile</p>
    </a>
</li>
<li>
    <a href="./tables.html">
        <i class="now-ui-icons design_bullet-list-67"></i>
        <p>Table List</p>
    </a>
</li>
<li>
    <a href="./typography.html">
        <i class="now-ui-icons text_caps-small"></i>
        <p>Typography</p>
    </a>
</li>
<li class="active-pro">
    <a href="./upgrade.html">
        <i class="now-ui-icons arrows-1_cloud-download-93"></i>
        <p>Upgrade to PRO</p>
    </a>
</li>
