<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 02/09/2018
 * Time: 9:39 AM
 */

class expenses{

    private static function Language(){

        if (isset($_SESSION['lang'])){
            $lang = $_SESSION['lang'];
        }else{
            $lang ="en";
        }
        return $lang;
    }

    public static function add_data($conn){

        $userID = $_SESSION["user-id"];
        $categoryID = $_POST['category'];
        $details = $_POST['detail'];
        $type = $_POST['type'];
        $ref = $_POST['ref'];
        $amount = $_POST['amount'];

        $lang = self::Language();

        $now = date("Y/m/d H:i:s");
        $date = date_create( $_POST['date']);
        $date = date_format($date,"Y/m/d");

        if ($categoryID === "Choose..." || $type === "Choose..."){
            header("location: index.php?page=expenses&lang=".$lang."&error=1&token=".$_SESSION['token']);
        }else {

            if ($type == 1) {
                $add = "INSERT INTO `ledge` (`userID`, `bookID`, `cataID`, `tan_date`, `sdate`, `detail`,`payID`, `ref`, `v_credit`, `b_credit`) 
VALUES ('$userID', '2', '$categoryID', '$now', '$date', '$details','$type' ,'$ref', '$amount', '$amount')";
                $result = $conn->query($add);
            } elseif ($type == 2) {
                $add = "INSERT INTO `ledge` (`userID`, `bookID`, `cataID`, `tan_date`, `sdate`, `detail`,`payID`, `ref`, `v_credit`, `c_credit`) 
VALUES ('$userID', '2', '$categoryID', '$now', '$date', '$details','$type' ,'$ref', '$amount', '$amount')";
                $result = $conn->query($add);
            } else {
                header("location: index.php?page=expenses&lang=" . $lang . "&error=1&token=" . $_SESSION['token']);
                exit();
            }

            if ($result == TRUE) {
                header("location: index.php?page=expenses&lang=" . $lang . "&token=" . $_SESSION['token']);
            } else {
                header("location: index.php?page=expenses&lang=" . $lang . "&error=1&token=" . $_SESSION['token']);
            }
        }
    }

    public static function edit_data($conn){

        $legID = $_SESSION['ledgerID'];
        $userID = $_SESSION["user-id"];

        $lang = self::Language();

        $now = date("Y-m-d H:i:s");
        $date = date_create( $_POST['date']);
        $date = date_format($date,"Y/m/d");

        $categoryID = $_POST['category'];
        $details = $_POST['detail'];
        $type = $_POST['type'];
        $ref = $_POST['ref'];
        $amount = $_POST['amount'];

        if ($type == 1){
            $sql ="UPDATE `ledge` SET `tan_date`='$now', `userID`='$userID', `bookID`='2', `cataID`='$categoryID', `sdate`='$date', `detail`='$details', `ref`='$ref', `v_credit`='$amount', `b_credit`='$amount' WHERE (`legID`='$legID')";
            $result = $conn->query($sql);
        }elseif ($type == 2){
            $sql ="UPDATE `ledge` SET `tan_date`='$now', `userID`='$userID', `bookID`='2', `cataID`='$categoryID', `sdate`='$date', `detail`='$details', `ref`='$ref', `v_credit`='$amount', `c_credit`='$amount' WHERE (`legID`='$legID')";
            $result = $conn->query($sql);
        }else{
            header("location: index.php?page=expenses&lang=".$lang."&error=1&token=".$_SESSION['token']);
            exit();
        }

        if ($result == TRUE){
            header("location: index.php?page=expenses&lang=".$lang."&token=".$_SESSION['token']);
        } else{
            header("location: index.php?page=expenses&lang=".$lang."&error=1&token=".$_SESSION['token']);
        }

    }

    public static function add_utilities_bill($conn){

        $userID = $_SESSION["user-id"];
        $categoryID = $_POST['category'];
        $details = $_POST['detail'];
        $type = $_POST['type'];
        $ref = $_POST['ref'];
        $amount = $_POST['amount'];

        $lang = self::Language();

        $now = date("Y/m/d H:i:s");
        $date = date_create( $_POST['date']);
        $date = date_format($date,"Y/m/d");

        if ($categoryID === "Choose..." || $type === "Choose..."){
            header("location: index.php?page=expenses&lang=".$lang."&error=1&token=".$_SESSION['token']);
        }else {

       $add = "INSERT INTO `utilities_bills` (`tran_date`, `cdate`,`userID`,`cataID`, `detail`,`ref`, `typeID`, `bills`) VALUES ('$now', '$date', '$userID','$categoryID', '$details', '$ref', '$type','$amount')";
       $result = $conn->query($add);

            if ($result == TRUE) {
                header("location: index.php?page=utilities-bill&lang=" . $lang . "&token=" . $_SESSION['token']);
            } else {
                header("location: index.php?page=utilities-bill&lang=" . $lang . "&error=1&token=" . $_SESSION['token']);
            }
        }
    }

    public static function edit_utilities_bill($conn){

        $legID = $_SESSION['ledgerID'];
        $userID = $_SESSION["user-id"];

        $lang = self::Language();

        $now = date("Y-m-d H:i:s");
        $date = date_create( $_POST['date']);
        $date = date_format($date,"Y/m/d");

        $categoryID = $_POST['category'];
        $details = $_POST['detail'];
        $type = $_POST['type'];
        $ref = $_POST['ref'];
        $amount = $_POST['amount'];

        $sql ="UPDATE `utilities_bills` SET `userID`='$userID', `tran_date`='$now', `cdate`='$date', `cataID`='$categoryID', `detail`='$details', `ref`='$ref', `typeID`='$type', `bills`='$amount' WHERE (`utilitiesID`='$legID')";
        $result = $conn->query($sql);

        if ($result == TRUE){
            header("location: index.php?page=utilities-bill&lang=".$lang."&token=".$_SESSION['token']);
        } else{
            header("location: index.php?page=utilities-bill&lang=".$lang."&error=1&token=".$_SESSION['token']);
        }

    }

}