<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 02/09/2018
 * Time: 9:39 AM
 */

class income{

    private static function Language(){

        if (isset($_SESSION['lang'])){
            $lang = $_SESSION['lang'];
        }else{
            $lang ="en";
        }
        return $lang;
    }

    public static function add_data($conn){

        $userID = $_SESSION["user-id"];
        $categoryID = $_POST['category'];
        $details = $_POST['detail'];
        $type = $_POST['type'];
        $ref = $_POST['ref'];
        $amount = $_POST['amount'];

        $lang = self::Language();
        $now = date("Y/m/d H:i:s");
        $date = date_create( $_POST['date']);
        $date = date_format($date,"Y/m/d");

         $add ="INSERT INTO `ledge` (`userID`, `bookID`, `cataID`, `tan_date`, `sdate`, `detail`,`payID`, `ref`, `debt`, `credit`) 
VALUES ('$userID', '1', '$categoryID', '$now', '$date', '$details','$type' ,'$ref', '$amount', '0')";
        $result = $conn->query($add);

        if ($result == TRUE){
            header("location: index.php?page=income&lang=".$lang."&token=".$_SESSION['token']);
        } else{
            header("location: index.php?page=income&lang=".$lang."&error=1&token=".$_SESSION['token']);
        }

    }

    public static function edit_data($conn){

        $now = date("Y-m-d H:i:s");
        $date = $_POST['date'];
        $userID = $_SESSION["user-id"];
        $categoryID = $_POST['category'];
        $details = $_POST['details'];
        $type = $_POST['payment'];
        $ref = $_POST['ref'];
        $amount = $_POST['amount'];

        $sql ="UPDATE `ledge` SET `userID`='$userID', `bookID`='$bookID', `cataID`='$categoryID', `sdate`='$date', `detail`='$details', `ref`='$ref', `debt`='$amount', `credit`='0' WHERE (`legID`='$legID')
VALUES ('$userID', '1', '$categoryID', '$now', '$date', '$details','$type' ,'$ref', '0', '$amount')";
        $result = $conn->query($sql);

    }

    public static function delete($conn){

        $legID = "";
        $userID ="";

        $sql ="DELETE FROM `ledge` WHERE (`legID`='$legID')";
        $result = $conn->query($sql);


    }

}