<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 02/09/2018
 * Time: 7:57 PM
 */

class Setting{

    public static function add_data($conn){

        $lang = $_SESSION['lang'];
        $userID = $_SESSION["user-id"];

        $type = $_POST['type'];
        $category = $_POST['category'];
        $description =$_POST['description'];

        $add="INSERT INTO `category` (`userID`, `category`,`description`, `bookID`) VALUES ('$userID','$category', '$description','$type')";
        $result = $conn->query($add);

        if ($result == TRUE){
            header("location: index.php?page=setting&lang=".$lang."&token=".$_SESSION['token']);
        } else{
            header("location: index.php?page=setting&lang=".$lang."&error=1&token=".$_SESSION['token']);
        }
    }

}