<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 08/09/2018
 * Time: 5:12 PM
 */

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$url = 'http://ipinfo.io/8.8.8.8?';

$c = curl_init();
curl_setopt($c,CURLOPT_URL,$url);
curl_setopt($c,CURLOPT_POST,true);
curl_setopt($c,CURLOPT_POSTFIELDS, 'token=7f54a31f0f9eac');
curl_setopt($c,CURLOPT_RETURNTRANSFER,true);
$content = curl_exec($c);
curl_close($c);
echo  $content;

