<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 01/09/2018
 * Time: 11:45 PM
 */

//set date
date_default_timezone_set('UTC');

//define setting
define('APPLICATION', "zACCOUNT");
define('VERSION',"");


//database connection
define('SERVER',"iquipe.heliohost.org");
define('USERNAME',"iquipe_zaccount4");
define('PASSWORD',"@iQuipe4299#");
define('DATABASE',"iquipe_zaccount");
define('PORT',"3306");
