<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 02/09/2018
 * Time: 9:32 PM
 */

include_once "model/bank.module";



?>
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        Bank
                        <a href="" class="btn btn-primary btn-sm">Deposit </a>
                        <a href="" class="btn btn-primary btn-sm">Withdrawal</a>
                        <a href="" class="btn btn-primary btn-sm">Bank Charges</a>
                        <button class="btn btn-primary btn-sm">Available Cash: <?php echo $u = bank::balance($conn);?>  </button>
                    </h4>
                </div>
                <div class="card-body">
                    <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" enctype="multipart/form-data">
                        <input type="hidden" name="submit" value="del banl">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-primary">
                                <th class="text-center">Date</th>
                                <th>Desperation</th>
                                <th>Ref. No#</th>
                                <th class="text-right">Debit</th>
                                <th class="text-right">Credit</th>
                                <th></th>
                                </thead>
                                <tbody>
                                <?php bank_book_sheet($conn);?>
                                </tbody>
                            </table>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
