<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 02/09/2018
 * Time: 10:43 PM
 */
?>

<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h5 class="title">Budget Slip</h5>
        </div>
        <div class="card-body">
            <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-6 pr-1">
                        <div class="form-group">
                            <label>Month</label>
                            <select name="month" id="inputState" class="form-control">
                                <option selected>Choose...</option>
                                <?php calender_month($conn);?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6 pr-1">
                        <div class="form-group">
                            <label>Year</label>
                            <select name="year" id="inputState" class="form-control">
                                <option selected>Choose...</option>
                                <?php calender_year($conn);?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 pr-1">
                        <div class="form-group">
                            <label>Ref#</label>
                            <input type="text" name="ref" readonly class="form-control" placeholder="" value="<?php echo "BS".rand();?>">
                        </div>
                    </div>
                    <div class="col-md-6 pr-1">
                        <div class="form-group">
                            <label>Budget Categories</label>
                            <select name="category" id="inputState" class="form-control">
                                <option selected>Choose...</option>
                                <?php expenses_categories($conn);?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Details</label>
                            <textarea rows="4" name="detail" cols="80" class="form-control" placeholder="Here can be your description"></textarea>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 pr-1">
                        <div class="form-group">
                            <label>Mode of payment</label>
                            <select name="type" id="inputState" class="form-control">
                                <option selected>Choose...</option>
                                <?php payment_type($conn);?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6 pr-1">
                        <div class="form-group">
                            <label>Amount</label>
                            <input type="number" name="amount" class="form-control" placeholder="0.00" value="">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 pr-1">
                        <button type="submit" name="submit" value="add budget" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="card card-user">
        <table class="table">
            <thead>
            <tr>
                <th>Period</th>
                <th>Budget</th>
                <th>Ref#</th>
                <th class="text-right">Amount</th>
                <th class="text-right">Actions</th>
            </tr>
            </thead>
            <tbody>
                <?php budget_book_sheet($conn);?>
            </tbody>
        </table>
        <hr>
        <div class="button-container">
            <button href="#" class="btn btn-neutral btn-icon btn-round btn-lg">
                <i class="fab fa-facebook-f"></i>
            </button>
            <button href="#" class="btn btn-neutral btn-icon btn-round btn-lg">
                <i class="fab fa-twitter"></i>
            </button>
            <button href="#" class="btn btn-neutral btn-icon btn-round btn-lg">
                <i class="fab fa-google-plus-g"></i>
            </button>
        </div>
    </div>
</div>