<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 03/09/2018
 * Time: 7:36 PM
 */

if (isset($_GET['token'])){
    $token = $_GET['token'];
}else{
    header("location:". $url->logout);
}

$sql ="SELECT * FROM `get_user` where token ='$token'";
$result = $conn->query($sql);
$rec = $result->fetch_assoc();

?>
<div class="col-md-8">
    <div class="card">
        <div class="card-header">
            <h5 class="title">Profile</h5>
        </div>
        <div class="card-body">
            <form>
                <div class="row">
                    <div class="col-md-3 pr-1">
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" class="form-control" placeholder="Username" value="<?php echo $rec['username'];?>">
                        </div>
                    </div>
                    <div class="col-md-4 pr-1">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Email address</label>
                            <input type="email" class="form-control" placeholder="Email" value="<?php echo $rec['email'];?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 pr-1">
                        <div class="form-group">
                            <label>First Name</label>
                            <input type="text" class="form-control" placeholder="Full Name" value="<?php echo $rec['fname'];?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Address</label>
                            <input type="text" class="form-control" placeholder="Home Address" value="<?php echo $rec['address'];?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 pr-1">
                        <div class="form-group">
                            <label>City</label>
                            <input type="text" class="form-control" placeholder="City" value="<?php echo $rec['city'];?>">
                        </div>
                    </div>
                    <div class="col-md-4 px-1">
                        <div class="form-group">
                            <label>Country</label>
                            <input type="text" class="form-control" placeholder="Country" value="<?php echo $rec['country'];?>">
                        </div>
                    </div>
                    <div class="col-md-4 pl-1">
                        <div class="form-group">
                            <label>Postal Code</label>
                            <input type="number" class="form-control" placeholder="ZIP Code" value="<?php echo $rec['postal'];?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>About Me</label>
                            <textarea rows="4" cols="80" class="form-control" placeholder="Here can be your description"><?php echo $rec['about'];?></textarea>
                        </div>
                    </div>
                </div>
                <button name="submit" type="button" value="profile-update" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="card card-user">
        <div class="image">
            <img src="plugin/assets2/img/bg5.jpg" alt="...">
        </div>
        <div class="card-body">
            <div class="author">
                <a href="#">
                    <img class="avatar border-gray" src="plugin/assets2/img/mike.jpg" alt="...">
                    <h5 class="title"><?php echo $rec['fname'];?></h5>
                </a>
                <p class="description">
                    <?php echo $rec['username'];?>
                </p>
            </div>
            <p class="description text-center">
                "Lamborghini Mercy
                <br> Your chick she so thirsty
                <br> I'm in that two seat Lambo"
            </p>
        </div>
        <hr>
        <div class="button-container">
            <button href="#" class="btn btn-neutral btn-icon btn-round btn-lg">
                <i class="fab fa-facebook-f"></i>
            </button>
            <button href="#" class="btn btn-neutral btn-icon btn-round btn-lg">
                <i class="fab fa-twitter"></i>
            </button>
            <button href="#" class="btn btn-neutral btn-icon btn-round btn-lg">
                <i class="fab fa-google-plus-g"></i>
            </button>
        </div>
    </div>
</div>

