<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 02/09/2018
 * Time: 4:12 AM
 */
?>
<div class="col-md-12">
    <div class="card">
        <div class="card-body">
            <div class="card text-center">
                <div class="card-header card-header-rose">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="true">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="income-tab" data-toggle="tab" href="#income" role="tab" aria-controls="income" aria-selected="false">Income</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="expenses-tab" data-toggle="tab" href="#expenses" role="tab" aria-controls="expenses" aria-selected="false">Expense</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#">Expense</a>
                        </li>
                    </ul>
                </div>
                <div class="tab-content" id="nav-tabContent">
                    <div class="card-body tab-pane fade show active" id="profile" role="tabpanel" >
                        <form>
                            <div class="col-xl-6">
                                <div class="form-group">
                                    <label for="inputAddress">Address</label>
                                    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
                                </div>
                            </div>
                            <div class="col-xl-6">
                                <button type="submit" class="btn btn-primary pull-left">Sign in</button>
                            </div>
                        </form>
                    </div>
                    <div class="card-body tab-pane fade" id="income" role="tabpanel">
                        <div class="col-md-12">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Category</th>
                                    <th>Description</th>
                                    <th class="text-right">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <?php income_category_sheet($conn);?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-body tab-pane fade" id="expenses" role="tabpanel">
                        <div class="col-md-12">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Category</th>
                                    <th>Description</th>
                                    <th class="text-right">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <?php expenses_category_sheet($conn);?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
